In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:.2f}".format)

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
pd.set_option("display.max_columns", None)

In [5]:
pd.set_option("display.max_rows", 100)

In [6]:
pd.set_option("display.float_format", "{:.2f}".format)

In [7]:
file_path = "../data/raw/WA_Fn-UseC_-HR-Employee-Attrition.csv"

df = pd.read_csv(file_path)

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

In [10]:
file_path = "../data/raw/WA_Fn-UseC_-HR-Employee-Attrition.csv"

df = pd.read_csv(file_path)

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

In [11]:
df.shape

(1470, 35)

In [12]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 1470
Columns: 35

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 510.8 KB

In [14]:
columns = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str),
    "Missing_Count": df.isnull().sum().values,
    "Unique_Values": df.nunique().values
})

columns

,Column,Data_Type,Missing_Count,Unique_Values
Age,Age,int64,0,43
Attrition,Attrition,str,0,2
BusinessTravel,BusinessTravel,str,0,3
DailyRate,DailyRate,int64,0,886
Department,Department,str,0,3
DistanceFromHome,DistanceFromHome,int64,0,29
Education,Education,int64,0,5
EducationField,EducationField,str,0,6
EmployeeCount,EmployeeCount,int64,0,1
EmployeeNumber,EmployeeNumber,int64,0,1470
EnvironmentSatisfaction,EnvironmentSatisfaction,int64,0,4
Gender,Gender,str,0,2
HourlyRate,HourlyRate,int64,0,71
JobInvolvement,JobInvolvement,int64,0,4
JobLevel,JobLevel,int64,0,5
JobRole,JobRole,str,0,9
JobSatisfaction,JobSatisfaction,int64,0,4
MaritalStatus,MaritalStatus,str,0,3
MonthlyIncome,MonthlyIncome,int64,0,1349
MonthlyRate,MonthlyRate,int64,0,1427
NumCompaniesWorked,NumCompaniesWorked,int64,0,10
Over18,Over18,str,0,1
OverTime,OverTime,str,0,2
PercentSalaryHike,PercentSalaryHike,int64,0,15
PerformanceRating,PerformanceRating,int64,0,2
RelationshipSatisfaction,RelationshipSatisfaction,int64,0,4
StandardHours,StandardHours,int64,0,1
StockOptionLevel,StockOptionLevel,int64,0,4
TotalWorkingYears,TotalWorkingYears,int64,0,40
TrainingTimesLastYear,TrainingTimesLastYear,int64,0,7
WorkLifeBalance,WorkLifeBalance,int64,0,4
YearsAtCompany,YearsAtCompany,int64,0,37
YearsInCurrentRole,YearsInCurrentRole,int64,0,19
YearsSinceLastPromotion,YearsSinceLastPromotion,int64,0,16
YearsWithCurrManager,YearsWithCurrManager,int64,0,18

In [15]:
missing = (
    df.isnull()
      .sum()
      .reset_index()
)

missing.columns = ["Column", "Missing_Count"]

missing["Missing_%"] = (
    missing["Missing_Count"] / len(df) * 100
)

missing.sort_values(
    "Missing_Count",
    ascending=False
)

                      Column  Missing_Count  Missing_%
0                        Age              0       0.00
1                  Attrition              0       0.00
2             BusinessTravel              0       0.00
3                  DailyRate              0       0.00
4                 Department              0       0.00
5           DistanceFromHome              0       0.00
6                  Education              0       0.00
7             EducationField              0       0.00
8              EmployeeCount              0       0.00
9             EmployeeNumber              0       0.00
10   EnvironmentSatisfaction              0       0.00
11                    Gender              0       0.00
12                HourlyRate              0       0.00
13            JobInvolvement              0       0.00
14                  JobLevel              0       0.00
15                   JobRole              0       0.00
16           JobSatisfaction              0       0.00
17             MaritalStatus              0       0.00
18             MonthlyIncome              0       0.00
19               MonthlyRate              0       0.00
20        NumCompaniesWorked              0       0.00
21                    Over18              0       0.00
22                  OverTime              0       0.00
23         PercentSalaryHike              0       0.00
24         PerformanceRating              0       0.00
25  RelationshipSatisfaction              0       0.00
26             StandardHours              0       0.00
27          StockOptionLevel              0       0.00
28         TotalWorkingYears              0       0.00
29     TrainingTimesLastYear              0       0.00
30           WorkLifeBalance              0       0.00
31            YearsAtCompany              0       0.00
32        YearsInCurrentRole              0       0.00
33   YearsSinceLastPromotion              0       0.00
34      YearsWithCurrManager              0       0.00

In [16]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [17]:
df["EmployeeNumber"].duplicated().sum()

np.int64(0)

In [18]:
df["Attrition"].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [19]:
df["Attrition"].value_counts(normalize=True) * 100

Attrition
No    83.88
Yes   16.12
Name: proportion, dtype: float64

In [20]:
attrition_summary = (
    df["Attrition"]
    .value_counts()
    .rename_axis("Attrition")
    .reset_index(name="Employees")
)

attrition_summary["Percentage"] = (
    attrition_summary["Employees"] / len(df) * 100
)

attrition_summary

  Attrition  Employees  Percentage
0        No       1233       83.88
1       Yes        237       16.12

In [21]:
attrition_rate = (
    df["Attrition"].eq("Yes").mean() * 100
)

print(f"Overall observed attrition rate: {attrition_rate:.2f}%")

Overall observed attrition rate: 16.12%

In [23]:
df.select_dtypes(include=["str"]).columns.tolist()

['Attrition',
 'BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'Over18',
 'OverTime']

In [25]:
categorical_cols = df.select_dtypes(
    include=["str"]
).columns.tolist()

categorical_cols

['Attrition',
 'BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'Over18',
 'OverTime']

In [26]:
numeric_cols = df.select_dtypes(
    include=np.number
).columns.tolist()

numeric_cols

['Age',
 'DailyRate',
 'DistanceFromHome',
 'Education',
 'EmployeeCount',
 'EmployeeNumber',
 'EnvironmentSatisfaction',
 'HourlyRate',
 'JobInvolvement',
 'JobLevel',
 'JobSatisfaction',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StandardHours',
 'StockOptionLevel',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager']

In [27]:
constant_columns = [
    col for col in df.columns
    if df[col].nunique() <= 1
]

constant_columns

['EmployeeCount', 'Over18', 'StandardHours']

In [28]:
constant_columns = [
    col for col in df.columns
    if df[col].nunique() <= 1
]

constant_columns

['EmployeeCount', 'Over18', 'StandardHours']

In [29]:
invalid_role_tenure = df[
    df["YearsInCurrentRole"] > df["YearsAtCompany"]
]

len(invalid_role_tenure)

0

In [30]:
invalid_manager_tenure = df[
    df["YearsWithCurrManager"] > df["YearsAtCompany"]
]

len(invalid_manager_tenure)

0

In [31]:
invalid_promotion = df[
    df["YearsSinceLastPromotion"] > df["YearsAtCompany"]
]

len(invalid_promotion)

0

In [32]:
invalid_working_years = df[
    df["TotalWorkingYears"] < df["YearsAtCompany"]
]

len(invalid_working_years)

0

In [33]:
df["Department"].value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [34]:
df["JobRole"].value_counts()

JobRole
Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: count, dtype: int64

In [35]:
df["OverTime"].value_counts()

OverTime
No     1054
Yes     416
Name: count, dtype: int64

In [36]:
df["BusinessTravel"].value_counts()

BusinessTravel
Travel_Rarely        1043
Travel_Frequently     277
Non-Travel            150
Name: count, dtype: int64

In [37]:
department_attrition = (
    pd.crosstab(
        df["Department"],
        df["Attrition"],
        normalize="index"
    ) * 100
)

department_attrition

Attrition                 No   Yes
Department
Human Resources        80.95 19.05
Research & Development 86.16 13.84
Sales                  79.37 20.63

In [38]:
jobrole_attrition = (
    pd.crosstab(
        df["JobRole"],
        df["Attrition"],
        normalize="index"
    ) * 100
)

jobrole_attrition.sort_values("Yes", ascending=False)

Attrition                    No   Yes
JobRole
Sales Representative      60.24 39.76
Laboratory Technician     76.06 23.94
Human Resources           76.92 23.08
Sales Executive           82.52 17.48
Research Scientist        83.90 16.10
Manufacturing Director    93.10  6.90
Healthcare Representative 93.13  6.87
Manager                   95.10  4.90
Research Director         97.50  2.50

In [39]:
jobrole_summary = (
    df.groupby("JobRole")
      .agg(
          Total_Employees=("EmployeeNumber", "count"),
          Attrition_Employees=("Attrition", lambda x: (x == "Yes").sum())
      )
)

jobrole_summary["Attrition_Rate_%"] = (
    jobrole_summary["Attrition_Employees"]
    / jobrole_summary["Total_Employees"]
    * 100
)

jobrole_summary.sort_values(
    "Attrition_Rate_%",
    ascending=False
)

,Total_Employees,Attrition_Employees,Attrition_Rate_%
JobRole,,,
Sales Representative,83,33,39.76
Laboratory Technician,259,62,23.94
Human Resources,52,12,23.08
Sales Executive,326,57,17.48
Research Scientist,292,47,16.10
Manufacturing Director,145,10,6.90
Healthcare Representative,131,9,6.87
Manager,102,5,4.90
Research Director,80,2,2.50

In [40]:
overtime_attrition = (
    pd.crosstab(
        df["OverTime"],
        df["Attrition"],
        normalize="index"
    ) * 100
)

overtime_attrition

Attrition    No   Yes
OverTime
No        89.56 10.44
Yes       69.47 30.53

In [41]:
travel_attrition = (
    pd.crosstab(
        df["BusinessTravel"],
        df["Attrition"],
        normalize="index"
    ) * 100
)

travel_attrition

Attrition            No   Yes
BusinessTravel
Non-Travel        92.00  8.00
Travel_Frequently 75.09 24.91
Travel_Rarely     85.04 14.96

In [2]:
import p

In [4]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:.2f}".format)

file_path = "../data/raw/WA_Fn-UseC_-HR-Employee-Attrition.csv"
df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 1470
Columns: 35

In [5]:
satisfaction_attrition = (
    pd.crosstab(
        df["JobSatisfaction"],
        df["Attrition"],
        normalize="index"
    ) * 100
)

satisfaction_attrition

Attrition          No   Yes
JobSatisfaction
1               77.16 22.84
2               83.57 16.43
3               83.48 16.52
4               88.67 11.33

In [6]:
environment_attrition = (
    pd.crosstab(
        df["EnvironmentSatisfaction"],
        df["Attrition"],
        normalize="index"
    ) * 100
)

environment_attrition

Attrition                  No   Yes
EnvironmentSatisfaction
1                       74.65 25.35
2                       85.02 14.98
3                       86.31 13.69
4                       86.55 13.45

In [7]:
worklife_attrition = (
    pd.crosstab(
        df["WorkLifeBalance"],
        df["Attrition"],
        normalize="index"
    ) * 100
)

worklife_attrition

Attrition          No   Yes
WorkLifeBalance
1               68.75 31.25
2               83.14 16.86
3               85.78 14.22
4               82.35 17.65

In [8]:
relationship_attrition = (
    pd.crosstab(
        df["RelationshipSatisfaction"],
        df["Attrition"],
        normalize="index"
    ) * 100
)

relationship_attrition

Attrition                   No   Yes
RelationshipSatisfaction
1                        79.35 20.65
2                        85.15 14.85
3                        84.53 15.47
4                        85.19 14.81

In [9]:
df["CareerStage"] = pd.cut(
    df["YearsAtCompany"],
    bins=[-1, 2, 5, 10, float("inf")],
    labels=[
        "Early Career",
        "Developing",
        "Established",
        "Long Tenure"
    ]
)

df["CareerStage"].value_counts()

CareerStage
Established     448
Developing      434
Early Career    342
Long Tenure     246
Name: count, dtype: int64

In [10]:
careerstage_attrition = (
    pd.crosstab(
        df["CareerStage"],
        df["Attrition"],
        normalize="index"
    ) * 100
)

careerstage_attrition

Attrition       No   Yes
CareerStage
Early Career 70.18 29.82
Developing   86.18 13.82
Established  87.72 12.28
Long Tenure  91.87  8.13

In [11]:
df["MonthlyIncome"].describe()

count    1470.00
mean     6502.93
std      4707.96
min      1009.00
25%      2911.00
50%      4919.00
75%      8379.00
max     19999.00
Name: MonthlyIncome, dtype: float64

In [12]:
df["IncomeBand"] = pd.cut(
    df["MonthlyIncome"],
    bins=[0, 3000, 6000, 10000, float("inf")],
    labels=[
        "Low Income",
        "Lower-Mid Income",
        "Upper-Mid Income",
        "High Income"
    ]
)

df["IncomeBand"].value_counts().sort_index()

IncomeBand
Low Income          395
Lower-Mid Income    519
Upper-Mid Income    275
High Income         281
Name: count, dtype: int64

In [13]:
income_attrition = (
    pd.crosstab(
        df["IncomeBand"],
        df["Attrition"],
        normalize="index"
    ) * 100
)

income_attrition

Attrition           No   Yes
IncomeBand
Low Income       71.39 28.61
Lower-Mid Income 87.28 12.72
Upper-Mid Income 88.00 12.00
High Income      91.10  8.90

In [14]:
income_summary = (
    df.groupby("IncomeBand", observed=True)
      .agg(
          Total_Employees=("EmployeeNumber", "count"),
          Attrition_Employees=("Attrition", lambda x: (x == "Yes").sum())
      )
)

income_summary["Attrition_Rate_%"] = (
    income_summary["Attrition_Employees"]
    / income_summary["Total_Employees"]
    * 100
)

income_summary

                  Total_Employees  Attrition_Employees  Attrition_Rate_%
IncomeBand
Low Income                    395                  113             28.61
Lower-Mid Income              519                   66             12.72
Upper-Mid Income              275                   33             12.00
High Income                   281                   25              8.90

In [15]:
joblevel_income = (
    df.groupby("JobLevel")
      .agg(
          Employees=("EmployeeNumber", "count"),
          Average_Income=("MonthlyIncome", "mean"),
          Median_Income=("MonthlyIncome", "median")
      )
      .round(2)
)

joblevel_income

          Employees  Average_Income  Median_Income
JobLevel
1               543         2786.92        2670.00
2               534         5502.28        5340.00
3               218         9817.25        9980.00
4               106        15503.78       16154.00
5                69        19191.83       19232.00

In [16]:
joblevel_attrition = (
    df.groupby("JobLevel")
      .agg(
          Total_Employees=("EmployeeNumber", "count"),
          Attrition_Employees=("Attrition", lambda x: (x == "Yes").sum())
      )
)

joblevel_attrition["Attrition_Rate_%"] = (
    joblevel_attrition["Attrition_Employees"]
    / joblevel_attrition["Total_Employees"]
    * 100
)

joblevel_attrition.round(2)

          Total_Employees  Attrition_Employees  Attrition_Rate_%
JobLevel
1                     543                  143             26.34
2                     534                   52              9.74
3                     218                   32             14.68
4                     106                    5              4.72
5                      69                    5              7.25

In [17]:
df["YearsAtCompany"].describe()

count   1470.00
mean       7.01
std        6.13
min        0.00
25%        3.00
50%        5.00
75%        9.00
max       40.00
Name: YearsAtCompany, dtype: float64

In [18]:
df["TenureBand"] = pd.cut(
    df["YearsAtCompany"],
    bins=[-1, 2, 5, 10, float("inf")],
    labels=[
        "0-2 Years",
        "3-5 Years",
        "6-10 Years",
        "10+ Years"
    ]
)

df["TenureBand"].value_counts().sort_index()

TenureBand
0-2 Years     342
3-5 Years     434
6-10 Years    448
10+ Years     246
Name: count, dtype: int64

In [19]:
tenure_attrition = (
    pd.crosstab(
        df["TenureBand"],
        df["Attrition"],
        normalize="index"
    ) * 100
)

tenure_attrition.round(2)

Attrition     No   Yes
TenureBand
0-2 Years  70.18 29.82
3-5 Years  86.18 13.82
6-10 Years 87.72 12.28
10+ Years  91.87  8.13

In [20]:
role_tenure_summary = (
    df.groupby("TenureBand", observed=True)
      .agg(
          Employees=("EmployeeNumber", "count"),
          Avg_YearsAtCompany=("YearsAtCompany", "mean"),
          Avg_YearsInCurrentRole=("YearsInCurrentRole", "mean"),
          Avg_YearsWithManager=("YearsWithCurrManager", "mean")
      )
      .round(2)
)

role_tenure_summary

,Employees,Avg_YearsAtCompany,Avg_YearsInCurrentRole,Avg_YearsWithManager
TenureBand,,,,
0-2 Years,342,1.24,0.73,0.68
3-5 Years,434,4.16,2.47,2.40
6-10 Years,448,8.18,5.74,5.64
10+ Years,246,17.92,9.43,9.17

In [21]:
df["RoleProgressionGap"] = (
    df["YearsAtCompany"] - df["YearsInCurrentRole"]
)

df[
    [
        "YearsAtCompany",
        "YearsInCurrentRole",
        "RoleProgressionGap",
        "Attrition"
    ]
].head(10)

   YearsAtCompany  YearsInCurrentRole  RoleProgressionGap Attrition
0               6                   4                   2       Yes
1              10                   7                   3        No
2               0                   0                   0       Yes
3               8                   7                   1        No
4               2                   2                   0        No
5               7                   7                   0        No
6               1                   0                   1        No
7               1                   0                   1        No
8               9                   7                   2        No
9               7                   7                   0        No

In [22]:
df["RoleProgressionBand"] = pd.cut(
    df["RoleProgressionGap"],
    bins=[-1, 2, 5, 10, float("inf")],
    labels=["0–2 Years", "3–5 Years", "6–10 Years", "10+ Years"]
)

df["RoleProgressionBand"].value_counts().sort_index()

RoleProgressionBand
0–2 Years     1033
3–5 Years      253
6–10 Years      92
10+ Years       92
Name: count, dtype: int64

In [23]:
progression_attrition = (
    df.groupby("RoleProgressionBand", observed=True)
      .agg(
          Employees=("EmployeeNumber", "count"),
          Attrition_Count=("Attrition", lambda x: (x == "Yes").sum())
      )
      .reset_index()
)

progression_attrition["Attrition_Rate"] = (
    progression_attrition["Attrition_Count"]
    / progression_attrition["Employees"]
    * 100
).round(2)

progression_attrition

  RoleProgressionBand  Employees  Attrition_Count  Attrition_Rate
0           0–2 Years       1033              188           18.20
1           3–5 Years        253               23            9.09
2          6–10 Years         92               15           16.30
3           10+ Years         92               11           11.96

In [24]:
promotion_summary = (
    df.groupby("YearsSinceLastPromotion")
      .agg(
          Employees=("EmployeeNumber", "count"),
          Attrition_Count=("Attrition", lambda x: (x == "Yes").sum())
      )
      .reset_index()
)

promotion_summary["Attrition_Rate"] = (
    promotion_summary["Attrition_Count"]
    / promotion_summary["Employees"]
    * 100
).round(2)

promotion_summary

    YearsSinceLastPromotion  Employees  Attrition_Count  Attrition_Rate
0                         0        581              110           18.93
1                         1        357               49           13.73
2                         2        159               27           16.98
3                         3         52                9           17.31
4                         4         61                5            8.20
5                         5         45                2            4.44
6                         6         32                6           18.75
7                         7         76               16           21.05
8                         8         18                0            0.00
9                         9         17                4           23.53
10                       10          6                1           16.67
11                       11         24                2            8.33
12                       12         10                0            0.00
13                       13         10                2           20.00
14                       14          9                1           11.11
15                       15         13                3           23.08

In [25]:
df["PromotionDelayBand"] = pd.cut(
    df["YearsSinceLastPromotion"],
    bins=[-1, 2, 5, 10, float("inf")],
    labels=["0–2 Years", "3–5 Years", "6–10 Years", "10+ Years"]
)

df["PromotionDelayBand"].value_counts().sort_index()

PromotionDelayBand
0–2 Years     1097
3–5 Years      158
6–10 Years     149
10+ Years       66
Name: count, dtype: int64

In [26]:
promotion_delay_attrition = (
    df.groupby("PromotionDelayBand", observed=True)
      .agg(
          Employees=("EmployeeNumber", "count"),
          Attrition_Count=("Attrition", lambda x: (x == "Yes").sum())
      )
      .reset_index()
)

promotion_delay_attrition["Attrition_Rate"] = (
    promotion_delay_attrition["Attrition_Count"]
    / promotion_delay_attrition["Employees"]
    * 100
).round(2)

promotion_delay_attrition

  PromotionDelayBand  Employees  Attrition_Count  Attrition_Rate
0          0–2 Years       1097              186           16.96
1          3–5 Years        158               16           10.13
2         6–10 Years        149               27           18.12
3          10+ Years         66                8           12.12

In [27]:
career_progression_summary = (
    df.groupby("PromotionDelayBand", observed=True)
      .agg(
          Employees=("EmployeeNumber", "count"),
          Avg_YearsAtCompany=("YearsAtCompany", "mean"),
          Avg_YearsInCurrentRole=("YearsInCurrentRole", "mean"),
          Avg_YearsSincePromotion=("YearsSinceLastPromotion", "mean"),
          Attrition_Rate=("Attrition", lambda x: (x == "Yes").mean() * 100)
      )
      .round(2)
)

career_progression_summary

,Employees,Avg_YearsAtCompany,Avg_YearsInCurrentRole,Avg_YearsSincePromotion,Attrition_Rate
PromotionDelayBand,,,,,
0–2 Years,1097,5.04,3.06,0.62,16.96
3–5 Years,158,11.46,7.42,3.96,10.13
6–10 Years,149,10.39,7.02,7.26,18.12
10+ Years,66,21.48,9.74,12.65,12.12

In [3]:
import os

print(os.getcwd())

C:\Users\MY PC\Desktop\HR-Analytics-Advanced\notebooks

In [4]:
import os

print(os.listdir(r"C:\Users\MY PC\Desktop\HR-Analytics-Advanced\data\raw"))

['WA_Fn-UseC_-HR-Employee-Attrition.csv']

In [5]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\MY PC\Desktop\HR-Analytics-Advanced\data\raw\WA_Fn-UseC_-HR-Employee-Attrition.csv"
)

print(df.shape)

(1470, 35)

In [6]:
job_satisfaction_summary = (
    df.groupby("JobSatisfaction")
      .agg(
          Employees=("EmployeeNumber", "count"),
          Attrition_Count=("Attrition", lambda x: (x == "Yes").sum())
      )
      .reset_index()
)

job_satisfaction_summary["Attrition_Rate"] = (
    job_satisfaction_summary["Attrition_Count"]
    / job_satisfaction_summary["Employees"]
    * 100
).round(2)

job_satisfaction_summary

   JobSatisfaction  Employees  Attrition_Count  Attrition_Rate
0                1        289               66           22.84
1                2        280               46           16.43
2                3        442               73           16.52
3                4        459               52           11.33

In [7]:
environment_satisfaction_summary = (
    df.groupby("EnvironmentSatisfaction")
      .agg(
          Employees=("EmployeeNumber", "count"),
          Attrition_Count=("Attrition", lambda x: (x == "Yes").sum())
      )
      .reset_index()
)

environment_satisfaction_summary["Attrition_Rate"] = (
    environment_satisfaction_summary["Attrition_Count"]
    / environment_satisfaction_summary["Employees"]
    * 100
).round(2)

environment_satisfaction_summary

   EnvironmentSatisfaction  Employees  Attrition_Count  Attrition_Rate
0                        1        284               72           25.35
1                        2        287               43           14.98
2                        3        453               62           13.69
3                        4        446               60           13.45

In [8]:
job_involvement_summary = (
    df.groupby("JobInvolvement")
      .agg(
          Employees=("EmployeeNumber", "count"),
          Attrition_Count=("Attrition", lambda x: (x == "Yes").sum())
      )
      .reset_index()
)

job_involvement_summary["Attrition_Rate"] = (
    job_involvement_summary["Attrition_Count"]
    / job_involvement_summary["Employees"]
    * 100
).round(2)

job_involvement_summary

   JobInvolvement  Employees  Attrition_Count  Attrition_Rate
0               1         83               28           33.73
1               2        375               71           18.93
2               3        868              125           14.40
3               4        144               13            9.03

In [9]:
relationship_satisfaction_summary = (
    df.groupby("RelationshipSatisfaction")
      .agg(
          Employees=("EmployeeNumber", "count"),
          Attrition_Count=("Attrition", lambda x: (x == "Yes").sum())
      )
      .reset_index()
)

relationship_satisfaction_summary["Attrition_Rate"] = (
    relationship_satisfaction_summary["Attrition_Count"]
    / relationship_satisfaction_summary["Employees"]
    * 100
).round(2)

relationship_satisfaction_summary

   RelationshipSatisfaction  Employees  Attrition_Count  Attrition_Rate
0                         1        276               57           20.65
1                         2        303               45           14.85
2                         3        459               71           15.47
3                         4        432               64           14.81

In [10]:
worklife_balance_summary = (
    df.groupby("WorkLifeBalance")
      .agg(
          Employees=("EmployeeNumber", "count"),
          Attrition_Count=("Attrition", lambda x: (x == "Yes").sum())
      )
      .reset_index()
)

worklife_balance_summary["Attrition_Rate"] = (
    worklife_balance_summary["Attrition_Count"]
    / worklife_balance_summary["Employees"]
    * 100
).round(2)

worklife_balance_summary

   WorkLifeBalance  Employees  Attrition_Count  Attrition_Rate
0                1         80               25           31.25
1                2        344               58           16.86
2                3        893              127           14.22
3                4        153               27           17.65

In [11]:
overtime_summary = (
    df.groupby("OverTime")
      .agg(
          Employees=("EmployeeNumber", "count"),
          Attrition_Count=("Attrition", lambda x: (x == "Yes").sum())
      )
      .reset_index()
)

overtime_summary["Attrition_Rate"] = (
    overtime_summary["Attrition_Count"]
    / overtime_summary["Employees"]
    * 100
).round(2)

overtime_summary

  OverTime  Employees  Attrition_Count  Attrition_Rate
0       No       1054              110           10.44
1      Yes        416              127           30.53

In [12]:
overtime_job_satisfaction = (
    df.groupby(["OverTime", "JobSatisfaction"])
      .agg(
          Employees=("EmployeeNumber", "count"),
          Attrition_Count=("Attrition", lambda x: (x == "Yes").sum())
      )
      .reset_index()
)

overtime_job_satisfaction["Attrition_Rate"] = (
    overtime_job_satisfaction["Attrition_Count"]
    / overtime_job_satisfaction["Employees"]
    * 100
).round(2)

overtime_job_satisfaction

  OverTime  JobSatisfaction  Employees  Attrition_Count  Attrition_Rate
0       No                1        205               36           17.56
1       No                2        211               20            9.48
2       No                3        321               32            9.97
3       No                4        317               22            6.94
4      Yes                1         84               30           35.71
5      Yes                2         69               26           37.68
6      Yes                3        121               41           33.88
7      Yes                4        142               30           21.13

In [13]:
overtime_worklife = (
    df.groupby(["OverTime", "WorkLifeBalance"])
      .agg(
          Employees=("EmployeeNumber", "count"),
          Attrition_Count=("Attrition", lambda x: (x == "Yes").sum())
      )
      .reset_index()
)

overtime_worklife["Attrition_Rate"] = (
    overtime_worklife["Attrition_Count"]
    / overtime_worklife["Employees"]
    * 100
).round(2)

overtime_worklife

  OverTime  WorkLifeBalance  Employees  Attrition_Count  Attrition_Rate
0       No                1         58               15           25.86
1       No                2        240               26           10.83
2       No                3        639               54            8.45
3       No                4        117               15           12.82
4      Yes                1         22               10           45.45
5      Yes                2        104               32           30.77
6      Yes                3        254               73           28.74
7      Yes                4         36               12           33.33

In [14]:
df["Overtime_Risk"] = (df["OverTime"] == "Yes").astype(int)

df["Low_JobSatisfaction"] = (df["JobSatisfaction"] == 1).astype(int)

df["Low_WorkLifeBalance"] = (df["WorkLifeBalance"] == 1).astype(int)

df["Low_JobInvolvement"] = (df["JobInvolvement"] == 1).astype(int)

In [15]:
df["Employee_Risk_Score"] = (
    df["Overtime_Risk"]
    + df["Low_JobSatisfaction"]
    + df["Low_WorkLifeBalance"]
    + df["Low_JobInvolvement"]
)

In [16]:
risk_summary = (
    df.groupby("Employee_Risk_Score")
      .agg(
          Employees=("EmployeeNumber", "count"),
          Attrition_Count=("Attrition", lambda x: (x == "Yes").sum())
      )
      .reset_index()
)

risk_summary["Attrition_Rate"] = (
    risk_summary["Attrition_Count"]
    / risk_summary["Employees"]
    * 100
).round(2)

risk_summary

   Employee_Risk_Score  Employees  Attrition_Count  Attrition_Rate
0                    0        759               54            7.11
1                    1        563              126           22.38
2                    2        139               51           36.69
3                    3          9                6           66.67

In [17]:
df["Risk_Segment"] = pd.cut(
    df["Employee_Risk_Score"],
    bins=[-1, 0, 1, 2, 4],
    labels=["Low Risk", "Moderate Risk", "High Risk", "Very High Risk"]
)

df["Risk_Segment"].value_counts()

Risk_Segment
Low Risk          759
Moderate Risk     563
High Risk         139
Very High Risk      9
Name: count, dtype: int64

In [18]:
risk_segment_summary = (
    df.groupby("Risk_Segment", observed=True)
      .agg(
          Employees=("EmployeeNumber", "count"),
          Attrition_Count=("Attrition", lambda x: (x == "Yes").sum())
      )
      .reset_index()
)

risk_segment_summary["Attrition_Rate"] = (
    risk_segment_summary["Attrition_Count"]
    / risk_segment_summary["Employees"]
    * 100
).round(2)

risk_segment_summary

     Risk_Segment  Employees  Attrition_Count  Attrition_Rate
0        Low Risk        759               54            7.11
1   Moderate Risk        563              126           22.38
2       High Risk        139               51           36.69
3  Very High Risk          9                6           66.67

In [19]:
df["Attrition_Binary"] = (
    df["Attrition"] == "Yes"
).astype(int)

In [20]:
correlation_cols = [
    "Age",
    "MonthlyIncome",
    "JobLevel",
    "YearsAtCompany",
    "YearsInCurrentRole",
    "YearsSinceLastPromotion",
    "YearsWithCurrManager",
    "JobSatisfaction",
    "EnvironmentSatisfaction",
    "JobInvolvement",
    "WorkLifeBalance",
    "Employee_Risk_Score",
    "Attrition_Binary"
]

correlation_matrix = (
    df[correlation_cols]
    .corr()["Attrition_Binary"]
    .sort_values(ascending=False)
)

correlation_matrix

Attrition_Binary           1.000000
Employee_Risk_Score        0.286891
YearsSinceLastPromotion   -0.033019
WorkLifeBalance           -0.063939
EnvironmentSatisfaction   -0.103369
JobSatisfaction           -0.103481
JobInvolvement            -0.130016
YearsAtCompany            -0.134392
YearsWithCurrManager      -0.156199
Age                       -0.159205
MonthlyIncome             -0.159840
YearsInCurrentRole        -0.160545
JobLevel                  -0.169105
Name: Attrition_Binary, dtype: float64

In [21]:
import os

processed_path = r"C:\Users\MY PC\Desktop\HR-Analytics-Advanced\data\processed\HR_Employee_Attrition_Cleaned.csv"

df.to_csv(processed_path, index=False)

print("Cleaned data saved successfully!")
print(processed_path)

Cleaned data saved successfully!
C:\Users\MY PC\Desktop\HR-Analytics-Advanced\data\processed\HR_Employee_Attrition_Cleaned.csv

In [22]:
os.path.exists(processed_path)

True